### ISSUE TITLE
Binary UUIDs Result in Empty Fields

### ISSUE THREAD

**Issue by arminlinzbauer** [DBDiff/DBDiff#126] opened 2021-12-15 09:51 UTC
When trying to diff two databases with BINARY data (in my case UUIDs), the resulting diff contains empty strings instead of the UUIDs - this effectively means SQL code like this, for example: a merge table:

```sql
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
INSERT INTO `mytable` VALUES('','','');
```

**Comment by jasdeepkhalsa** [comment] 2021-12-15 11:23
Closing as a duplicate of #127

**Closed by jasdeepkhalsa** 2021-12-15 11:23 UTC
